
import os
import time
import subprocess
import glob

# Configuration
SLURM_DIR = "/home/phanim/harshitrawat/summer"
USER = "harshitrawat"
MAX_PENDING = 2  # Conservative limit
CHECK_INTERVAL = 60 # Seconds

def get_queue_count():
    try:
        # Count lines in squeue output (minus header)
        result = subprocess.run(
            ["squeue", "--user", USER, "--noheader"], 
            capture_output=True, text=True
        )
        return len(result.stdout.strip().split('\n')) if result.stdout.strip() else 0
    except Exception as e:
        print(f"Error checking queue: {e}")
        return 999 # Safe fallback

def main():
    # Identify all target slurm files
    # We look for the patterns generated by generate_embedding_slurms.py
    # Pattern: embed_T*.slurm
    # Exclude debug ones
    slurm_files = sorted(glob.glob(os.path.join(SLURM_DIR, "embed_T*.slurm")))
    
    print(f"Found {len(slurm_files)} jobs to submit.")
    
    for i, slurm_file in enumerate(slurm_files):
        job_name = os.path.basename(slurm_file)
        
        while True:
            current_jobs = get_queue_count()
            print(f"[{time.strftime('%H:%M:%S')}] Queue: {current_jobs} / {MAX_PENDING}")
            
            if current_jobs < MAX_PENDING:
                # Submit
                print(f"Submitting {job_name} ({i+1}/{len(slurm_files)})...")
                subprocess.run(["sbatch", slurm_file])
                # Small sleep to let scheduler update
                time.sleep(5)
                break
            else:
                # Wait
                time.sleep(CHECK_INTERVAL)

if __name__ == "__main__":
    main()
